//
//  Opportunity_List.m
//  sfa
//
//  Created by Admin on 27/02/14.
//  Copyright (c) 2014 ttl. All rights reserved.
//

#import "Opportunity_List.h"

Opportunity_List *opportunity_list;
NSMutableArray *OpportunityListArr;
NSMutableArray *OpportunityListDisplayArr;

@implementation Opportunity_List

@synthesize OPTY_ID,CONTACT_ADDRESS,ADDRESS_ID,OPTY_NAME,PRODUCT_LINE,PARENT_PROD_LINE,VC,SALES_STAGE_DATE,SALE_STAGE_NAME,OPTY_CREAT_DATE,
            CONTACT_ID,CONTACT_NAME,CONTACT_CELL_NUMBER,ACCOUNT_PHONE_NUMBER,ACCOUNT_ID,ACCOUNT_NAME,ACCOUNT_LOCATION,MAKE_LOST_TO,MODEL_LOST_TO,
CLOSURE_SUMMARY,REASON_LOST,RNUM,RESULT_COUNT,PRODUCT_NAME1,
PRODUCT_ID,
TGM_TKM_NAME,
TGM_TKM_PHONE_NUMBER,
ACCOUNT_TYPE,LEAD_ASSIGNED_NAME,
LEAD_ASSIGNED_CELL_NUMBER,
LEAD_POSITION,
LEAD_ASSIGNED_POSITION_ID,CONTACT_FIRST_NAME,
CONTACT_LAST_NAME,
LAST_PENDING_ACTIVITY_TYPE,
LAST_PENDING_ACTIVITY_ID,
LAST_PENDING_ACTIVITY_STATUS,LAST_PEND_ACTIVIY_START_DATE,
LAST_PENDING_ACTIVITY_DESC,LAST_DONE_ACTIVITY_DATE,
CUSTOMER_ACCOUNT_NAME,
CUSTOMER_ACCOUNT_ID,
CUSTOMER_PHONE_NUMBER,
CUSTOMER_ACCOUNT_LOCATION,
REV_PRODUCT_ID,PRODUCT_NAME,
LAST_DONE_ACTIVITY_TYPE,
LAST_DONE_ACTIVITY_DESC;


@end
