//
//  SearchActivity_List.m
//  sfa
//
//  Created by Admin on 08/04/14.
//  Copyright (c) 2014 ttl. All rights reserved.
//

#import "SearchActivity_List.h"


SearchActivity_List *searchActivity_list;
NSMutableArray *SearchActivitiesListArray;
NSMutableArray *DisplaySearchActivitiesDetailsArray;


@implementation SearchActivity_List

//@synthesize OPTY_NAME,OPTY_ID,PRODUCT_NAME,PARENT_PRODUCT_NAME,OPTY_CREATED,ACTIVITY_COMPLETION_DATE,ACTIVITY_STATUS,
//            DESCRIPTION,OPTY_CREAT_DATE,OPPTY_ROWID,OPPTY_NAME,PRODUCT_LINE,VC,CONTACT_ID,CONTACT_NAME,CONTACT_CELL_NUM,
//            CONTACT_ADDRESS,ADDRESS_ID,ACCOUNT_ID,ACCOUNT_NAME,ACCOUNT_PHONE_NUMBER,ACCOUNT_LOCATION,SALES_STAGE_DATE,SALE_STAGE,RNUM,RESULT_COUNT,LEAD_ASSIGNED_NAME,LEAD_ASSIGNED_CELL_NUMBER,LEAD_ASSIGNED_POSITION_NAME,LEAD_ASSIGNED_POSITION_ID,ACTIVITY_PENDING_TYPE,PLANNED_START_DATE,ACTIVITY_ID,ACTIVITY_DESCRIPTION,X_TALUKA,X_PROSPECT_SRC;

@synthesize ACTIVITY_ROW_ID,ACTIVITY_TYPE,ACTIVITY_PLAN_START_DATE,ACTIVITY_CREATED_DATE,ACTIVITY_COMPLETION_DATE,ACTIVITY_STATUS,
DESCRIPTION,OPTY_CREAT_DATE,OPPTY_ROWID,OPPTY_NAME,PARENT_PRODUCT_NAME,PRODUCT_LINE,VC,CONTACT_ID,CONTACT_NAME,CONTACT_CELL_NUM,
CONTACT_ADDRESS,ADDRESS_ID,ACCOUNT_ID,ACCOUNT_NAME,ACCOUNT_PHONE_NUMBER,ACCOUNT_LOCATION,SALES_STAGE_DATE,SALE_STAGE,RNUM,RESULT_COUNT;

@end
